### ISSUE TITLE
ProgressTimer or ProgressFromTo compilation error

### ISSUE THREAD

**Issue by aksh1203** [cocos2d/cocos2d-x#19412]
- cocos2d-x version: 3.17 / 3.17.1
- devices test on: Mi Max 2
- developing environments
   - NDK version: For 3.17.1 - 16b, For 3.17 - 19.0.5232133 [From Cocos2dX Forum]
   - Xcode version: NA
   - VS version: NA
   - browser type and version: NA

Steps to Reproduce:

Add ProgressTimer or ProgressFromTo related codes and compile.

Even though I compiled successfully this code on v3.17 but the same block of code did not compile on v3.17.1.

Probable Solution - 
Add this line to your LOCAL_SRC_FILES := $(LOCAL_PATH)/…/…/…/cocos2d/cocos/ui/UILoadingBar.cpp

More Details - https://discuss.cocos2d-x.org/t/cocos2dx-3-17-android-compile-time-error/45686

@slackmoehrle

**Comment by DonMizzi** [comment]
Same error here. Up!

**Comment by aksh1203** [comment]
> Same error here. Up!

You add the header file of progresstimer including path.
