### ISSUE TITLE
Undefined symbols for architecture x86_64: "typeinfo for cocos2d::Controller"

### ISSUE THREAD

**Issue by HellFighter** [cocos2d/cocos2d-x#18545]
- cocos2d-x version: 3.16 (7916beb314)
- devices test on: Mac
- developing environments
   - Xcode version: 9.1 (9B55)

Steps to Reproduce:

1. Clone cocos2d-x repo
2. Download deps and update submodules
3. Create new JS project ( cocos new MyGame -p com.MyCompany.MyGame -l js -d MyGameJS )
4. Generate Xcode project from CMake ( cmake -GXcode )
5. Try to build MyGame application via Xcode

After successful compilation linker fails with error:
> Undefined symbols for architecture x86_64:
  "typeinfo for cocos2d::Controller", referenced from:
      js_type_class* js_get_type_from_native<cocos2d::Controller>(cocos2d::Controller*) in libjscocos2d.a(jsb_cocos2dx_auto.o)
ld: symbol(s) not found for architecture x86_64

If build application like this
> cocos run -p mac

everything goes well

**Comment by dumganhar** [comment]
Yep, cmake build is only tested on Linux. I don't confirm that it could work on other platforms.
You could use `build/cocos2d_tests.xcodeproj` for building test-case.
Or use `proj.ios_mac/your_project_name.xcodeproj` to build your game.

**Comment by HellFighter** [comment]
Could you please fix this issue on mac build? I really wanna have one cmake build system instead of one new for each platform

**Comment by dumganhar** [comment]
@drelaptop is working on CMAKE for all platforms. He may help you. :)

**Comment by drelaptop** [comment]
have supported cmake build on macOS, cocos2d-x version: 3.17 https://github.com/cocos2d/cocos2d-x/commit/4675ee79cd134ca63c8fd258c4e8a49f14fe9639

please close this issue @minggo
