### PR TITLE
No throws in cocos2d-x code

### PR DESCRIPTION
**Pull request by ricardoquesada**
No throws in cocos2d-x code

### CODE REVIEW

File: cocos/base/allocator/CCAllocatorGlobalNewDelete.cpp [hunk 1]
```diff
@@ -28,6 +28,8 @@
 #include <new>
 #include <exception>
 
+#include "base/ccMacros.h"
```
Comment (samuele3hu) [inline cocos/base/allocator/CCAllocatorGlobalNewDelete.cpp:31]: This sentence would lead to compile error on the win32 platform for libcocos2d project.Because WinSock2.h is included behind the windows.h.The error message as follows:
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\ws2def.h(212): error C2011: 'sockaddr' : 'struct' type redefinition
....
Can we put the `include "base/ccMacros.h"` in the beginning of this file?

**Comment by ricardoquesada** [comment]
I sent this new PR:
https://github.com/cocos2d/cocos2d-x/pull/11722

@minggo do you know why Jenkins didn't detect this compilation issue? thanks

**Comment by zilongshanren** [comment]
@ricardoquesada  I'm fixing the Jenkins problem.
Some bad commits are merged into Jenkins... And Jenkins seems not work for git error.

**Comment by ricardoquesada** [comment]
@andyque ok. thanks.
