### ISSUE TITLE
HELP! XMLHttpRequest reponseText become to unreadable character(mojibake)!

### ISSUE THREAD

**Issue by lp43** [cocos2d/cocos2d-x#3436]
I used XMLHttpRequest to POST something and want to get return value of Chinese character with JSON format, but I got unreadable character(UTF-8 format).

To figure out my problem simply,
I send chinese character from XMLHttpRequest.cpp(C++ side) directly as below:

JS_BINDED_PROP_GET_IMPL(MinXmlHttpRequest, responseText)
{
//    JSString\* str = JS_NewStringCopyZ(cx, data.str().c_str());//, dataSize);
      JSString\* str = JS_NewStringCopyZ(cx, "我愛測試");//, dataSize);

```
if (str) {
    vp.set(STRING_TO_JSVAL(str));
    //JS_ReportError(cx, "Result: %s", data.str().c_str());
    return JS_TRUE;
} else {
    JS_ReportError(cx, "Error trying to create JSString from data");
    return JS_FALSE;
}
```

}

and XHRTest.js(javascript side) I wrote:

 sendPostRequest: function() {

```
    var that = this;
    var xhr = new XMLHttpRequest();
    var statusPostLabel = cc.LabelTTF.create("Status:", "Thonburi", 18);
    this.addChild(statusPostLabel, 1);

    statusPostLabel.setPosition(cc.p(winSize.width / 2, winSize.height - 160));
    statusPostLabel.setString("Status: Send Post Request to httpbin.org");

                               xhr.onreadystatechange = function() {

                               cc.log("TEST POST: xhr.onreadystatechange..., status: " + xhr.status);
                               var httpStatus = xhr.statusText;

                               var bytes = xhr.responseText;
                               cc.log("newtext: "+bytes);   //print the Chinese character result from XMLHttpRequest.cpp when sent "亂碼測試" 

                               var response = xhr.responseText.substring(0,100) + "...";
                               cc.log("header:"+xhr.getResponseHeader("Content-Type"));

                               var responseLabel = cc.LabelTTF.create("POST Response (100 chars):  \n" + response, "Thonburi", 16);
                               that.addChild(responseLabel, 1);

                               responseLabel.setPosition(cc.p(350, winSize.height - 220));
                               statusPostLabel.setString("Status: Got POST response! " + httpStatus);

                               }

    sys.garbageCollect();
    this.scheduleOnce(function(){
        cc.log("POST: GC in next frame...");
        sys.garbageCollect();
    });
},
```

still the unreadable character appeared.

![javascript_character](https://f.cloud.github.com/assets/338229/991856/dcad246c-096f-11e3-9041-7f8225530c34.png)

Please refer to javascript/TestJavaScript sample from cocos2dx samples folder that I try to test is.

Thanks!

Environment: Xcode4.6.3,Cocos2dx2.1.4,Mac Lion

**Comment by dumganhar** [comment]
Thanks for your feedback, I will test it.

**Comment by dumganhar** [comment]
Fixed at https://github.com/dumganhar/cocos2d-x/commit/f5ae6a77ea02aeea1486b815922f596fe8b606c8
Please test and give me feedback. Thanks.

**Comment by lp43** [comment]
in XMLHttpRequest.h

   enum class ResponseType{
        STRING,
        ARRAY_BUFFER,
        BLOB,
        DOCUMENT,
        JSON
    };

return Expected identifier or '{'
Declaration does not declare anything

What's this mean?
Thanks!

Environment: Xcode4
.6.3 with Cocos2dx 2.1.4

**Comment by dumganhar** [comment]
Hi @lp43 
I only fixed the issue in the latest codes on github.
So if you want to make it works on v2.1.4. You should refer to https://github.com/dumganhar/cocos2d-x/commit/f5ae6a77ea02aeea1486b815922f596fe8b606c8 .

**Comment by dumganhar** [comment]
`enum class` is only supported in `c++11`.

**Comment by lp43** [comment]
_James
*
*Two questions.
*
*1.
std_string_to_jsval(cx, data.str()); *
this usage in v2.1.4 return No matching function for call to
'std_string_to_jsval',
so I change to
*c_string_to_jsval(cx, data.str().c_str());_

_2._
Line 327
_JSString *tmpstr = JS_NewStringCopyZ(cx, "1");
jsval tmpval = STRING_TO_JSVAL(tmpstr); *
Doesn't need to change to
*jsval tmpval = c_string_to_jsval(cx, "1");
?_

2.1.4 version modified here
https://github.com/lp43/cocos2d-x/commit/5ab0f31a47d289fa3db44b39566fcc8dd1e589dc#scripting/javascript/bindings

2013/8/20 James Chen notifications@github.com

> enum class is only supported in c++11.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cocos2d/cocos2d-x/issues/3436#issuecomment-22945142
> .

## 

座佑銘︰我之所以成功是因為我_務實_。

**Comment by dumganhar** [comment]
1) In cocos2d-x 2.1.4, the definition of `std_string_to_jsval` is 

```
jsval std_string_to_jsval(JSContext* cx, string& v); // You could change it to `const string& v`, then it will not generate compilation errors.
```

2) As you see, "1" is an ASCII letter. so it doesn't need to use `std_string_to_jsval`.

**Comment by dumganhar** [comment]
If there is not other problem, please close this issue , thanks.

**Comment by lp43** [comment]
Closed.
Thanks!
2013/8/21 ¤U¤È12:52 ©ó "James Chen" notifications@github.com ¼g¹D¡G
