### ISSUE TITLE
Erro	2	error C1083: Cannot open include file: 'zlib.h': No such file or directory	D:\Repos\JogoDeAventuras\cocos2d\cocos\editor-support\cocostudio\CocoLoader.cpp	2	1	libCocosStudio

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8504]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/5679). It was created at 2014/07/07 18:42:36 +0000
# Description
- orlando2bjr added comment:
  Damn, I pressed enter while typing this issue and it was published too soon :-(
  I'm really sorry. :( 

After upgrading my projects to 3.2 RC0;
Try to build the wp8 project and you get the following error: 

<blockquote>
Erro    2   error C1083: Cannot open include file: 'zlib.h': No such file or directory  D:\Repos\JogoDeAventuras\cocos2d\cocos\editor-support\cocostudio\CocoLoader.cpp 2   1   libCocosStudio
</blockquote>

The file exists, but, somehow, it was not found by the project linking settings.
